name: Build, Test, Analyze, and Push Docker Image11

on:
    push:
        branches:
            - main

jobs:
    build-test-analyze:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:latest
                ports:
                    - 5432:5432
                env:
                    POSTGRES_DB: gestion_examens
                    POSTGRES_USER: geb_spring_app
                    POSTGRES_PASSWORD: 340$Uuxwp7Mcxo7Khy
                options: >-
                    --health-cmd="pg_isready -U geb_spring_app -d gestion_examens"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=5

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Set up JDK 21
                uses: actions/setup-java@v3
                with:
                    java-version: '21'
                    distribution: 'temurin'

            -   name: Wait for PostgreSQL
                run: |
                    until pg_isready -h localhost -p 5432 -U geb_spring_app; do
                    echo "Waiting for PostgreSQL to be ready..."
                    sleep 5
                    done

            -   name: Clear SonarQube cache
                run: rm -rf ~/.sonar/cache

            -   name: Build and Test
                run: mvn clean verify

            -   name: Analyze with SonarQube
                run: |
                    mvn sonar:sonar \
                    -Dsonar.projectKey=gestion-examens \
                    -Dsonar.host.url=https://879a-197-3-209-3.ngrok-free.app \
                    -Dsonar.login=admin \
                    -Dsonar.password="Admin55307062." \
                    -Dsonar.scanner.forceUpload=true

            -   name: Upload build artifacts
                uses: actions/upload-artifact@v3
                with:
                    name: build-artifacts
                    path: target/

    docker-build:
        runs-on: ubuntu-latest
        needs: build-test-analyze

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Download build artifacts
                uses: actions/download-artifact@v3
                with:
                    name: build-artifacts

            -   name: Log in to Docker Hub
                uses: docker/login-action@v2
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}

            -   name: Build Docker image
                run: docker build -t ${{ secrets.DOCKER_USERNAME }}/gestion-examens:latest .

            -   name: Push Docker image
                run: docker push ${{ secrets.DOCKER_USERNAME }}/gestion-examens:latest